version: '3.8'

services:
      docker-proxy-manager:
            build:
                  context: .
                  dockerfile: Dockerfile
            container_name: docker-proxy-manager
            network_mode: "host"
            volumes:
                  # 挂载Docker socket以控制宿主机Docker
                  - /var/run/docker.sock:/var/run/docker.sock
                  # 挂载Docker CLI工具
                  - /usr/bin/docker:/usr/bin/docker:ro
                  - ./docker_manager.py:/app/docker_manager.py
                  - ./service.json:/app/service.json
            environment:
                  - PYTHONUNBUFFERED=1
                  - PYTHONDONTWRITEBYTECODE=1
            restart: always
            logging:
                  driver: "json-file"
                  options:
                        max-size: "10m"
                        max-file: "3"

      nginx:
            image: openresty/openresty:alpine
            container_name: nginx-proxy
            # 使用宿主机网络；容器内 127.0.0.1 == 宿主机 127.0.0.1
            network_mode: "host"
            volumes:
                  - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
                  - nginx_logs:/var/log/nginx
            restart: always
            command: [ "/usr/local/openresty/bin/openresty", "-g", "daemon off;" ]

volumes:
      nginx_logs:
